require 'test_helper'

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::BrandQueriesControllerTest < ActionController::TestCase

  # Replace this with your real tests.
  test "the truth" do
    assert true
  end

end