# Typus Roles Configuration File
#
# In this file you can configure the actions available for each of your 
# models on the application.
#
#     admin:
#       Post: create, read, update, delete
#       Category: create, read, update, delete
#
#     editor:
#       Post: create, read, update
#       Category: read, update
#
# You can also define `resources` which are not related to a model, 
# for example to control MemCached or see the Starling queue statistics.
#
#     admin:
#      Starling: index
#      MemCached: index, cleanup
#

admin:
  Account: create, read, update, delete
  Brand: create, read, update, delete
  BrandQuery: create, read, update, delete
  BrandResult: create, read, update, delete
  Invitation: create, read, update, delete
  Query: create, read, update, delete
  Result: create, read, update, delete
  SearchResult: create, read, update, delete
  Team: create, read, update, delete
  User: create, read, update, delete
