# app/config/application.yml
defaults: &defaults
  host: "brandizzle.com"
  pagination:
    results_per_page: 15
  invitations:
    limit: 0

development:
  <<: *defaults
  host: "brandizzle.local"
    
test:
  <<: *defaults
  host: "example.com"

cucumber:
  <<: *defaults
  host: "example.com"

aissac:
  <<: *defaults
  host: brandizzle.aissac.ro