# app/config/application.yml
defaults: &defaults
  host: "brandizzle.com"
  pagination:
    results_per_page: 15
    logs_per_page: 15
  invitations:
    limit: 0
  twitter:
    consumer_key: "foo_consumer_key"
    consumer_secret: "foo_consumer_secret"
  braintree:
    environment: :sandbox
    merchant_id: h6h56phxnnyhhj56
    public_key: 76wdmh6hhfpf3d5m
    private_key: 92nsjcq8f9ynrj9q

development:
  <<: *defaults
  host: "brandizzle.local"
  twitter:
    consumer_key: DOaquy8EyO07RXzqDbKFA
    consumer_secret: Z4aO0rrOFaNOXWgs9zRIhZvP5BCJK7nEVkfXGPHOo
    
test:
  <<: *defaults
  host: "example.com"

cucumber:
  <<: *defaults
  host: "example.com"

aissac:
  <<: *defaults
  host: brandizzle.aissac.ro
  twitter:
    consumer_key: DOaquy8EyO07RXzqDbKFA
    consumer_secret: Z4aO0rrOFaNOXWgs9zRIhZvP5BCJK7nEVkfXGPHOo