# app/config/application.yml
defaults: &defaults
  host: "brandizzle.com"
  pagination:
    results_per_page: 15

development:
  <<: *defaults
  host: "brandizzle.local"
    
test:
  <<: *defaults
  host: "example.com"

cucumber:
  <<: *defaults
  host: "example.com"

production:
  <<: *defaults
