# app/config/application.yml
defaults: &defaults
  standard:
    price: 29
    trial: 30
    members: 2
    searches: 6
    description: Standard
    id: standard
  comped:
    price: 0
    description: Comped
    id: comped

development:
  <<: *defaults
  standard:
    price: 29
    trial: 30
    members: 2
    searches: 10
    description: Standard
    id: standard
  comped:
    price: 0
    description: Comped
    id: comped
    
test:
  <<: *defaults

cucumber:
  <<: *defaults

aissac:
  <<: *defaults

production:
  standard:
    price: 29
    members: 2
    trial: 30
    searches: 10
    description: Standard
    id: standard
  comped:
    price: 0
    description: Comped
    id: comped